### ISSUE TITLE
Implement interactive data visualization using R and RMarkdown

### ISSUE THREAD

**Issue by ateucher** [bcgov/msw-disposal-indicator#1]
This issue is for a paid opportunity through the [BCDevExchange](https://bcdevexchange.org/). To apply, visit the [opportunity page](https://bcdevexchange.org/opportunities/cwu/opp-municipal-solid-waste-data-visualization-using-r) and submit a proposal by 16:00 Pacific Time, Wednesday, September 26, 2018.

---

Replicate and Enhance the existing D3 (JavaScript) data visualization on Municipal Solid Waste Disposal using [R](https://r-project.org) and [R Markdown](https://rmarkdown.rstudio.com/).

Please see the existing Municipal Solid Waste interactive data visualization: [Municipal Solid Waste - Environmental Reporting BC](http://www.env.gov.bc.ca/soe/indicators/sustainability/municipal-solid-waste.html). The project will replicate the current functionality and enhance it by adding a spatial (map-based) component.

#### Data Visualization Design/Layout

Datavis design (sketch below) should include existing vertical bar chart showing current year Municipal Solid Waste (MSW) estimates by regional district, side-by-side with a choropleth map of regional districts coloured by current year MSW estimates (enhancement). It should be 900px wide, and not more than 900px high.

![6927fb44](https://user-images.githubusercontent.com/2816635/45721753-3678b380-bb5e-11e8-89ca-fde34c2c871a.png)
![22b68d1c](https://user-images.githubusercontent.com/2816635/45721774-4c867400-bb5e-11e8-9f30-82b6b18827e0.png)

#### Functionality

- Hovering mouse over a bar in the bar chart, or polygon on the map, should highlight the other and bring up a tooltip with current year MSW estimate and population size for that regional district. See sketch.
- Vertical bar chart should have current sorting capabilities (by population or msw estimate or regional district name).
- Clicking on a bar or polygon should open a modal window with RD name, current year population and MSW estimate (all text), plus bar chart with historical and current year MSW estimates and image links for existing waste reports (similar to the right-hand chart and links in the existing visualization). See sketch.

#### Technologies

- Solution should be done using R and R Markdown that renders an html file.
- Anticipated/suggested packages and approaches include `plotly`, `crosstalk`,`Leaflet for R`, and the `tidyverse` collection of packages. We are open to other suggestions, however we are not seeking a _Shiny_ implementation at this time.

#### Resources

- The data used for the indicator (disposal rates and population) will be obtained from the [B.C. Data Catalogue](https://catalogue.data.gov.bc.ca/dataset/d21ed158-0ac7-4afd-a03b-ce22df0096bc)
- The links for the individual Regional District reports is in the [GitHub Repository](https://github.com/bcgov/msw-disposal-indicator/blob/master/data/rd_report_links.csv)
- Regional district boundaries for use in the map are available in the [bcmaps R package](https://cran.r-project.org/package=bcmaps)

**Comment by ateucher** [comment]
Hi folks, I am the contact for this Code With Us opportunity. Please post any questions you have here and I'll do my best to respond promptly.

**Comment by kiwinesian** [comment]
Hello there,

Just wondering if the repo is missing a file /data/2016_disposal_rates.csv ?
Or is it something that we need to download/ fetch during the execution?

**Comment by ateucher** [comment]
Hi @kiwinesian. The sources for all of the data required for the visualization is listed under **Resources** in the above description. The disposal rates specifically are sourced from this [BC Data Catalogue record](https://catalogue.data.gov.bc.ca/dataset/d21ed158-0ac7-4afd-a03b-ce22df0096bc) (direct link to the csv [here](https://catalogue.data.gov.bc.ca/dataset/d21ed158-0ac7-4afd-a03b-ce22df0096bc/resource/d2648733-e484-40f2-b589-48192c16686b/download/bcmunicipalsolidwastedisposal.csv)).

I probably could have been more specific in the description, but you don't actually need to run any of the existing code in the repository to create the visualization.

I hope that helps,
Andy

**Comment by kiwinesian** [comment]
Hi @ateucher, thanks so much for the prompt response! :)

I was interested in running to see if I can create the visualization first to better understand the requirements.
I did download the file and the filename is bcmunicipalsolidwastedisposal.csv - the expected filename is 2016_disposal_rates.csv
The code seems to bind the 2 files together and put store it on msw matrix.
It seems like bcmunicipalsolidwastedisposal.csv is the _latest_ data that is going to be binded with an old data.

Definitely interested in helping out. :)

Thanks so much, @ateucher

**Comment by ateucher** [comment]
Hi @kiwinesian. As documented in the [README](https://github.com/bcgov/msw-disposal-indicator/blob/master/README.md#code), the `internal.R` script is what we use internally to update the data on DataBC when new data is collected each year.  So the file `2016_disposal_rates.csv` is something we have internally, and it's appended to the previous year's `bcmunicipalsolidwastedisposal.csv` to create the current year's `bcmunicipalsolidwastedisposal.csv` (which we then post to the BC Data Catalogue).

Thanks again for your interest,
Andy

**Comment by ateucher** [comment]
Thanks to everyone for your interest in helping us out with this Code With Us opportunity.

The opportunity closed on Sept 26—we received 5 proposals. All proposals were scored against the proposal evaluation criteria. The opportunity has been assigned to @sebdalgarno who had the highest scoring proposal.

If you would like feedback on your proposal, please feel free to contact me at andy.teucher@gov.bc.ca.

Thanks again to everyone.

**Comment by ateucher** [comment]
Closed by #3
