### ISSUE TITLE
responsive ui

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/msw-disposal-indicator#14]
there are two options:
1. responsive UI
Resizes plots with window resizing. The problem with this is that the aspect ratio remains the same (as it should) so as the window becomes narrower, the white space between the upper and lower plots becomes large. Unfortunately the map and horizontal bar chart are 'one plot' in order for the linked hovering to work, so we can't get them to stack vertically when the window gets smaller.
![responsive_ui](https://user-images.githubusercontent.com/15878432/47888313-0846ee80-de01-11e8-85d1-43ecc8a81b81.gif)

2. Fixed UI. 
Plots are fixed in divs of 900px wide and centred. As window gets smaller than 900px, the user has to scroll to the right to see everything. This looks nicer as the space between the plots remains the same.
![fixed_ui](https://user-images.githubusercontent.com/15878432/47888352-4cd28a00-de01-11e8-8fda-1d729557c6dd.gif)

Personally I think option 2 is better.

**Comment by ateucher** [comment]
I think so too. There aren't many screens out there any more that are less than 900px wide.
