### ISSUE TITLE
map improvements

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/msw-disposal-indicator#4]
1. intersect regional district with `bc_bounds()` to eliminate need for overlay.
2. change projection to 3005
3. simplify to improve performance

**Comment by sebdalgarno** [comment]
done above - will leave open if any other improvements come up
<img width="404" alt="screen shot 2018-10-31 at 3 25 32 pm" src="https://user-images.githubusercontent.com/15878432/47822406-48cf3b00-dd21-11e8-9732-71e46e021618.png">

**Comment by sebdalgarno** [comment]
what are your thoughts on colour gradient? I tried to match the blue color of the bar chart (by getting shades and tints of that hex) but it ended up looking quite grey...

**Comment by ateucher** [comment]
It is quite grey... I'm open to suggestions on all colours. We tend to use colorbrew2.org a lot. I quite like `"Blues"` or `"GnBu"`; and you could match the bar chart to that?

**Comment by sebdalgarno** [comment]
<img width="730" alt="screen shot 2018-10-31 at 4 11 31 pm" src="https://user-images.githubusercontent.com/15878432/47823925-be3e0a00-dd27-11e8-915e-5daf4d4ef46f.png">

**Comment by sebdalgarno** [comment]
better I think...that is colorbrewer Blues palette

**Comment by ateucher** [comment]
I think that looks really nice. Any suggestions for the green and orange that won't clash with the blue? Keeping in mind that since it's encoding population and not waste disposal rates it should not be blue so as to not confuse people.

**Comment by sebdalgarno** [comment]
<img width="738" alt="screen shot 2018-10-31 at 4 34 51 pm" src="https://user-images.githubusercontent.com/15878432/47824637-feeb5280-dd2a-11e8-8885-e5711c75f689.png">

**Comment by sebdalgarno** [comment]
perhaps that is better. That is using the palette from the original viz, but a better method for generating gradient

**Comment by sebdalgarno** [comment]
assuming that the original palette didn't clash...

**Comment by ateucher** [comment]
I think it's looking good now. I still don't love the green and orange but that's also something we can fiddle around with on our end later.
