### ISSUE TITLE
speed up plot load

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/msw-disposal-indicator#6]
check whether possible to reduce amount of time takes to load the map and horizontal bar chart.
simplifying bc coastline further does not seem to help

**Comment by sebdalgarno** [comment]
removed any NA Disposal_Rate from indicator dataset so that ggplot2 doesn't have to...minor improvement I think

**Comment by sebdalgarno** [comment]
simplified coastline further

**Comment by ateucher** [comment]
Looking better! I think the regional districts could handle more simplification as well. I played around a bit and `keep = 0.005` still looks good.

**Comment by sebdalgarno** [comment]
OK great I'll change to 0.005

**Comment by sebdalgarno** [comment]
As far as I can tell, no more can be done without resorting to another package for plot build. Current speed is manageable IMO
